const kDIFFICULTY = 'difficulty' // difficulty
const kEASY = 'easy' // difficulty
const kHARD = 'hard' // difficulty
const kRAW = 'raw' // the raw loaded data (for habitats)
const kONLY_ANIMAL = 'only animals' // session storage
const kHASHES = 'hashes' // hashes for name : hash of name
const kLAST_HABITAT = 'last habitat' // the last habitat that was shown (to avoid repition)
const kLAST_ANIMALS = 'last animals' // the last animals that were shown (to avoid repition)
const kANIM_SEL = 'animal selected' // what animal is currently selected
const kHAB_SEL = 'habitat selected' // what habitat is currently selected
const kANIM_SEL_HASH = 'selected animal hash' // the hash of the animal that was selected
const kSEL_COMPARE = 'sel compare' // the hash of the animal name
const kANIM_SLIDES = 'animal slides' // the slides of more photos of animals to be shown during the info card
const kMAX_CARDS = 3 // how many cards to have
const kWIN_THRES = 3 // a threshold for how many they have to get right to win
const kCORRECT = 'correct count' // how many are correct
const kINFO_CARD_LIST = 'info cards' // list of all three info cards
// const kINFO_CURRENT_ANIM = 'current animal' // the current animal with an info card
